"""Initial migration.

Revision ID: 26422f1f63d0
Revises:
Create Date: 2024-04-06 21:23:08.882030

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26422f1f63d0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=25), nullable=True),
        sa.Column("city", sa.String(length=40), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("timezone", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_location_city"), ["city"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_location_country"), ["country"], unique=False
        )

    op.create_table(
        "device",
        sa.Column("hardware_id", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(length=20), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("exceptions", sa.JSON(), nullable=True),
        sa.Column("predefined_temperatures", sa.JSON(), nullable=True),
        sa.Column("predefined_labels", sa.JSON(), nullable=True),
        sa.Column("standard_week", sa.JSON(), nullable=True),
        sa.Column("dhw_programs", sa.JSON(), nullable=True),
        sa.Column("ta", sa.Integer(), nullable=True),
        sa.Column("dim", sa.Integer(), nullable=True),
        sa.Column("sl", sa.Integer(), nullable=True),
        sa.Column("sd", sa.Integer(), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("host", sa.String(length=17), nullable=True),
        sa.Column("measured_temperature", sa.Integer(), nullable=True),
        sa.Column("outside_temperature", sa.Integer(), nullable=True),
        sa.Column("outside_temperature_timestamp", sa.Integer(), nullable=True),
        sa.Column("set_temperature", sa.Integer(), nullable=True),
        sa.Column("source", sa.Integer(), nullable=True),
        sa.Column("ui_synced", sa.Boolean(), nullable=True),
        sa.Column("ui_source", sa.String(length=40), nullable=True),
        sa.Column("fw", sa.Integer(), nullable=True),
        sa.Column("hw", sa.Integer(), nullable=True),
        sa.Column("cal_synced", sa.Boolean(), nullable=True),
        sa.Column("cal_version", sa.Integer(), nullable=True),
        sa.Column(
            "creation_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("oo", sa.Integer(), nullable=True),
        sa.Column("ot0", sa.Integer(), nullable=True),
        sa.Column("ot1", sa.Integer(), nullable=True),
        sa.Column("ot3", sa.Integer(), nullable=True),
        sa.Column("ot17", sa.Integer(), nullable=True),
        sa.Column("ot18", sa.Integer(), nullable=True),
        sa.Column("ot19", sa.Integer(), nullable=True),
        sa.Column("ot25", sa.Integer(), nullable=True),
        sa.Column("ot26", sa.Integer(), nullable=True),
        sa.Column("ot27", sa.Integer(), nullable=True),
        sa.Column("ot28", sa.Integer(), nullable=True),
        sa.Column("ot34", sa.Integer(), nullable=True),
        sa.Column("ot56", sa.Integer(), nullable=True),
        sa.Column("ot125", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("hardware_id"),
    )
    with op.batch_alter_table("device", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_device_password"), ["password"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_device_password"))

    op.drop_table("device")
    with op.batch_alter_table("location", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_country"))
        batch_op.drop_index(batch_op.f("ix_location_city"))

    op.drop_table("location")
    # ### end Alembic commands ###
